#!/usr/bin/env bash
. "$(dirname -- "$0")/_/husky.sh"

# makes the script fail out if any single command fails
set -e;

# build script
npm run build;
npx sort-package-json package.json;

git add package.json;